SUPABASE_URL = "https://grwnyjdmqkimkpemutyd.supabase.co"
SUPABASE_KEY = "sb_publishable_yMI9u15ic0Vs3wr-bHGZGQ_wyaHbyE3"

GMAIL_EMAIL = "guptashanu277@gmail.com"
GMAIL_APP_PASSWORD = "elli tnee ancl veuz"